Hotfix custom sql filter inserttags
MetaModels/core pull request #1490
Opened 2023-01-24 19:29 UTC by Ainschy

## Description
fixes the problem with strung together and nested inserttags

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [x] Created tests, if possible
- [x] All tests passing
- [x] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [x] Checked the changes with phpcq and introduced no new issues

2023-01-24 20:09 UTC, zonky2 commented
@discordier workss fine for https://github.com/MetaModels/core/issues/880#issue-103936641 a) and workaround)

2023-01-25 14:35 UTC, discordier requested changes
Please change the methods to private

2023-01-25 14:35 UTC, discordier commented on src/Filter/Setting/CustomSql.php
> +    public function convertParameter($strMatch)
Can be made private now and the `@internal` can be removed. This method is now being called from `$this->checkTag()`.

2023-01-25 14:35 UTC, discordier commented on src/Filter/Setting/CustomSql.php
> +    public function parseAndAddSecureInsertTagAsParameter($strMatch)
Can be made private now and the `@internal` can be removed. This method is now being called from `$this->checkTag()`.

2023-01-25 16:21 UTC, discordier approved these changes

2023-01-29 20:51 UTC, merged